module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|@react-native|@react-native-firebase|@react-navigation|expo(nent)?|@expo(nent)?|expo-modules-core|react-clone-referenced-element|react-native-svg|native-base|react-native-tts|expo-font|expo-asset|react-native-vector-icons|react-native-fs|react-native-image-picker|@react-native-async-storage)/',
  ],
  setupFiles: ['<rootDir>/jest.setup.js'],
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
  //setupFiles: ['<rootDir>/__tests__/helpers/setup-jest.js'],
  moduleNameMapper: {
    '^~/(.*)$': '<rootDir>/src/$1',
    '^@expo/vector-icons/?(.*)$': 'react-native-vector-icons/$1',
    '^@react-native-firebase/(.*)$': '<rootDir>/node_modules/@react-native-firebase/$1',
  },
  testMatch: [
    '**/__tests__/**/*.test.js?(x)',
    '**/__tests__/**/*.test.ts?(x)',
    '<rootDir>/detox/tests/**/*.test.js',
  ],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/components/organisms/*.{ts,tsx}',
    'src/services/*.{ts,tsx}',
    'src/services/firebase/*.{ts,tsx}',
    'src/hooks/useQRCodeAdmin.ts',
    '!src/services/PermissionService.ts',
    '!**/__tests__/**',
    '!**/index.{ts,tsx}',
    '!**/*.d.ts',
    '!src/components/organisms/AdminFloorplanEditorContent.tsx',
    '!src/components/organisms/ManageUsersForm.tsx',
    '!src/components/organisms/AdminIndoorPositioningContent.tsx',
    //'!src/components/organisms/QRCodeAdminContent.tsx',
    '!src/components/organisms/MapActionsPanel.tsx',
    '!src/components/organisms/IndoorNavigationInstructionsContent.tsx',
    '!src/components/organisms/BeaconPositioningFlow.tsx',
    '!src/components/organisms/BluetoothBuildingsContent.tsx',
    '!src/components/organisms/BluetoothIndoorNavigationContent.tsx',
    '!src/components/organisms/FloorplanEditor.tsx',
    '!src/components/organisms/IndoorSchematicNavContent.tsx',
    '!src/components/organisms/RoomsListOverlay.tsx',
    '!src/components/organisms/ShopContent.tsx',
    '!src/components/organisms/TimetableContent.tsx',
    '!src/components/organisms/TimetableSection.tsx',
    '!src/services/NotificationService.ts',
    '!src/services/WiFiPositioningService.ts',
    '!src/services/scanService.ts',
    '!src/services/CacheService.ts',
    '!src/services/firebase/floorplanService.ts',
    'src/utils/*.{ts,tsx}',
    '!src/utils/cacheUtils.ts',
    '!src/utils/helpers.ts',
    '!src/utils/pathUtils.ts',
  ],
  coverageDirectory: 'coverage',
};
